export let treeBoard = [
  ["", "", "", "", "", "gray", "", "", "", "", ""],
  ["", "", "", "", "gray", "green", "gray", "", "", "", ""],
  ["", "", "", "gray", "green blue", "green", "green", "gray", "", "", ""],
  [
    "",
    "",
    "gray",
    "green",
    "green",
    "green",
    "green red",
    "green",
    "gray",
    "",
    "",
  ],
  ["", "", "", "gray", "green", "darkgreen", "green", "gray", "", "", ""],
  [
    "",
    "",
    "gray",
    "green",
    "darkgreen",
    "green",
    "darkgreen",
    "green",
    "gray",
    "",
    "",
  ],
  [
    "",
    "gray",
    "green",
    "green red",
    "green",
    "green yellow",
    "green",
    "green gray",
    "green",
    "gray",
    "",
  ],
  [
    "",
    "",
    "gray",
    "green",
    "darkgreen",
    "green",
    "darkgreen",
    "green",
    "gray",
    "",
    "",
  ],
  [
    "",
    "gray",
    "green",
    "darkgreen",
    "green",
    "darkgreen",
    "green",
    "darkgreen",
    "green yellow",
    "gray",
    "",
  ],
  [
    "gray",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "green",
    "gray",
  ],
  [
    "",
    "gray",
    "green yellow",
    "green",
    "green blue",
    "green",
    "green",
    "green red",
    "green",
    "gray",
    "",
  ],
  ["", "", "gray", "gray", "gray", "brown", "gray", "gray", "gray", "", ""],
  ["", "", "", "", "gray", "gray", "gray", "", "", "", ""],
];
